# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Set variables once
variables:
  svc.name.k8s.namespace: mysql.development

trigger:
- master

pool:
  name: Azure Pipelines
  demands: maven

steps:
- task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
  displayName: 'Replace MySql service name and k8s namespace in Springboot config file'
  inputs:
    sourcePath: src/main/resources
    filePattern: '*.properties'
    tokenRegex: '__(\w+[.\w+]*)__'

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    options: '-DskipITs'
    testResultsFiles: '**/TEST-*.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactsstagngdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **/*.jar
     **/*.yaml
    TargetFolder: '$(build.artifactsstagngdirectory)'

- task: DockerCompose@0
  displayName: 'Build container image'
  inputs:
    azureSubscription: 'DevOps(a76f26df-c81c-4fd6-b976-ba04f91c777a)'
    azureContainerRegistry: '{"loginServer":"nvpdevopsaks.azurecr.io", "id" : "/subscriptions/a76f26df-c81c-4fd6-b976-ba04f91c777a/resourceGroups/nvp-devops-aks-rg/providers/Microsoft.ContainerRegistry/registries/nvpdevopsaks"}'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeLatestTag: true

- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    azureSubscription: 'DevOps(a76f26df-c81c-4fd6-b976-ba04f91c777a)'
    azureContainerRegistry: '{"loginServer":"nvpdevopsaks.azurecr.io", "id" : "/subscriptions/a76f26df-c81c-4fd6-b976-ba04f91c777a/resourceGroups/nvp-devops-aks-rg/providers/Microsoft.ContainerRegistry/registries/nvpdevopsaks"}'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeLatestTag: true